### PR TITLE
Double-map the nuget path

### LINKED ISSUE #3305: App cannot read mounted NuGet packages from /root/.nuget/packages when using generated Dockerfile
I am attempting to debug a .NET Container Linux container from my Windows 10 machine. The Dockerfile was generated by this extension when running `Docker: Add Docker Files to Workspace`. 

Upon running debug using the generated launch item `Docker .NET Core Launch`, this extension runs the container for debugging, but the NuGet packages folder is mounted to `/root/.nuget/packages` inside the container. This is a problem because the Dockerfile generated by this extension runs the app as `appuser` rather than `root` (which is best practice). Therefore, the app can neither resolve or access the mounted NuGet packages folder at `/root/.nuget/packages`. This results in an inability for the app to access the mounted .nuget/packages and any `staticwebassets`.

Steps to Reproduce (repro repo: https://github.com/dwoldo/repro-root-vscode-debug)
1. dotnet new console
2. code \<console app folder\>
3. Open command pallet (Windows: CTRL + SHIFT + P), select `Docker: Add Docker Files to Workspace...`
4. Choose `.NET: Core Console App` for "Select Application Platform" prompt
5. Choose `Linux` for "Select Operating System" prompt
6. Choose `No` for "Include optional Docker compose files?" prompt.
7. Open the generated Dockerfile and observe line 6 and 7, running as `appuser`
   image
7. From "Run and Debug" start debugging `Docker: .NET Core Launch`
8. From "docker-run: debug" terminal display, observe the volume mount `-v "C:\Users\<Username>\.nuget\packages:/root/.nuget/packages:ro"`:

   ```docker run -dt -P --name "reprorootvscodedebug-dev" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" --label "com.microsoft.created-by=visual-studio-code" -v "C:\repos\throwaway\repro-root-vscode-debug:/app:rw" -v "c:\repos\throwaway\repro-root-vscode-debug:/src:rw" -v "C:\Users\<Username>\.vsdbg:/remote_debugger:ro" -v "C:\Users\<Username>\.nuget\packages:/root/.nuget/packages:ro" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro" "reprorootvscodedebug:dev"```

Work Around:
1. Remove Line 6 and 7 from Dockerfile (not recommended).

Possible Fix:
1. Replace all hard-coded paths for `/root/.nuget` in https://github.com/microsoft/vscode-docker/blob/4e7ba64d90204cc9b18ef068cda6b64ccc282fa5/src/tasks/netcore/NetCoreTaskHelper.ts with the dynamic user read-in from Dockerfile seen here: https://github.com/microsoft/vscode-docker/blob/4e7ba64d90204cc9b18ef068cda6b64ccc282fa5/src/tasks/netcore/NetCoreTaskHelper.ts#L262

### PR DESCRIPTION
**Pull request by bwateratmsft**
Should fix #3305

### CODE REVIEW

File: src/tasks/netcore/NetCoreTaskHelper.ts [hunk 1]
```diff
@@ -223,36 +219,23 @@ export class NetCoreTaskHelper implements TaskHelper {
...
-                if (programFilesEnvironmentVariable === undefined) {
-                    throw new Error(localize('vscode-docker.tasks.netCore.programFilesUndefined', 'The environment variable \'ProgramFiles\' is not defined. This variable is used to locate the NuGet fallback folder.'));
-                }
-            }
-
-            const nugetFallbackVolume: DockerContainerVolume = {
-                localPath: isWindows() ? path.join(programFilesEnvironmentVariable, 'dotnet', 'sdk', 'NuGetFallbackFolder') :
-                    (isMac() ? MacNuGetPackageFallbackFolderPath : LinuxNuGetPackageFallbackFolderPath),
-                containerPath: runOptions.os === 'Windows' ? 'C:\\.nuget\\fallbackpackages' : '/root/.nuget/fallbackpackages',
+            const nugetUserVolume: DockerContainerVolume = {
```
Comment (bwateratmsft) [inline src/tasks/netcore/NetCoreTaskHelper.ts:228]: I'm not totally sure this volume mapping is even necessary for Windows; I think `ContainerUser` can access `C:\.nuget\packages`?

Comment (bwateratmsft) [reply src/tasks/netcore/NetCoreTaskHelper.ts:228]: In fact it looks like maybe we should always have been doing this: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file

**Review by karolz-ms — APPROVED** [review]
For posterity: the NuGet fallback folder volume is removed because it is no longer used by newer versions of .NET. See https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows#remove-the-nuget-fallback-folder for reference
