### PR TITLE
Fix missing os: Windows in dockerRun config

### LINKED ISSUE #1735: .NET Core Debug fails on Windows containers
Debugging .NET Core on Windows containers is failing. The error is in docker-run-execute, `docker: Error response from daemon: invalid volume specification: 'd:\Sandbox\NetWindows:/src:rw'.`

image

The issue is that `"dockerRun": { "os": "Windows" }` is missing, probably since 0.10.0.

**Workaround**
In the `"dockerRun"` section of the `tasks.json` config, put `"os": "Windows"`. For example:
```json
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build: debug"
            ],
            "dockerRun": {
                "os": "Windows"
            },
            "netCore": {
                "appProject": "${workspaceFolder}/NetWindows.csproj",
                "enableDebugging": true
            }
        },
```

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #1735.

### CODE REVIEW

File: src/configureWorkspace/configureDotNetCore.ts [hunk 1]
```diff
@@ -386,7 +386,7 @@ async function initializeForDebugging(context: IActionContext, folder: Workspace
 
 // tslint:disable-next-line: export-name
 export async function scaffoldNetCore(context: ScaffolderContext): Promise<ScaffoldFile[]> {
-    const os = context.os ?? await context.promptForOS();
```
Comment (philliphoff) [inline src/configureWorkspace/configureDotNetCore.ts]: An alternative fix would be to not use `context.os` after this point (in favor of the local `os` value), which was likely my intent at the time.
