### PR TITLE
Fix some Python hot reload issues

### LINKED ISSUE #2050: It opens 2 webpages when debugging Django project with hot reloading enabled on Windows
**OS:** Windows 10
**Build Version:** 20200604.7

**Repro Steps:**
1. Open a Django app in VS Code.
2. F1 -> Docker: Add Docker Files to Workspace -> Python: Django -> Include docker compose files.
3. Enable hot reloading.
4. F5.

**Expect:**
Debug successfully and open 1 webpage.

**Actual:**
Debug successfully and it opens 2 webpages.

**More Info:**
1. This issue does not reproduce with hot reloading disabled.
2. This issue does not reproduce in Flask project.
3. This issue does not reproduce on Mac.

### LINKED ISSUE #2148: Debugger stops on hot reload for Flask in debugger
Issue Type: <b>Bug</b>

## Steps to reproduce problem:

1. launch.json configuration as given below:
```
{
            "name": "Docker: Python - Flask",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}/web/",
                        "remoteRoot": "/app"
                    }
                ],
                "host": "localhost",
                "port": 5000,
                "projectType": "flask",
            },
            "removeContainerAfterDebug": true}
        }
```

task.json given below:

```
{
			"type": "docker-build",
			"label": "docker-build",
			"platform": "python",
			"dockerBuild": {
				"tag": "<tag name removed>",
				"dockerfile": "${workspaceFolder}/web/Dockerfile",
				"context": "${workspaceFolder}/web/",
				"pull": true
			}
		},
		{
			"type": "docker-run",
			"label": "docker-run: debug",
			"dependsOn": [
				"docker-build"
			],
			"dockerRun": {
				"containerName": "<container name removed>",
				"env": {
					"FLASK_APP": "<app name removed>",
					"FLASK_ENV": "development",
					"FLASK_DEBUG": "1"
				},
				"volumes": [
					{
					  "containerPath": "/app", "localPath": "${workspaceFolder}/web/"
					},
				],
				"envFiles": [
					"${workspaceFolder}/web/.env"
				],
				"ports": [
					{
						"containerPort": 5000, "hostPort": 5000
					}
				]
			},
			"python": {
				"args": [
					"run",
					"--host",
					"0.0.0.0",
					"--port",
					"5000",
				],
				"module": "flask",
			}
		}
```

2. Run debugger 
3. Make edit anywhere on a python file and save

## Results

Expected results:
Flask hot reloads.

Actual results:
Last line in debug console is:

`* Detected change in '/<python file name>.py', reloading`

and then the debugger simply stops.

Apologies but I do not have a code snippet available for copying!

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2050, fixes #2148.

Definitely for 1.5.0 (not 1.4.0)

### CODE REVIEW

File: src/debugging/DockerDebugConfigurationProvider.ts [hunk 1]
```diff
@@ -143,7 +142,7 @@ export class DockerDebugConfigurationProvider implements DebugConfigurationProvi
             const disposable = debug.onDidStartDebugSession(async session => {
                 const sessionConfiguration = <ResolvedDebugConfiguration>session.configuration;
 
-                // Don't do anything if this isn't our debug session
+                // Don't do anything if this isn't our debug session (which is how Python does hot reload sessions)
```
Comment (bwateratmsft) [inline src/debugging/DockerDebugConfigurationProvider.ts:145]: Wrong place for this comment

File: src/debugging/DockerServerReadyAction.ts [hunk 2]
```diff
@@ -289,15 +289,17 @@ class MultiOutputDockerServerReadyManager extends vscode.Disposable implements D
...
 
 class DockerDebugAdapterTrackerFactory implements vscode.DebugAdapterTrackerFactory {
-    private static trackers: Map<vscode.DebugSession, MultiOutputDockerServerReadyManager> = new Map<vscode.DebugSession, MultiOutputDockerServerReadyManager>();
+    private static trackers: Map<string, MultiOutputDockerServerReadyManager> = new Map<string, MultiOutputDockerServerReadyManager>();
 
     public static start(session: vscode.DebugSession): DockerDebugAdapterTracker | undefined {
         const configuration = <ResolvedDebugConfiguration>session.configuration;
         if (configuration?.dockerOptions?.dockerServerReadyAction) {
-            let tracker = DockerDebugAdapterTrackerFactory.trackers.get(session);
+            const realSessionId = configuration?.__sessionId as string || session.id;
```
Comment (karolz-ms) [inline src/debugging/DockerServerReadyAction.ts:297]: Consider using a utility function to calculate `realSessionId` (the same expression shows up twice in the code)
