### PR TITLE
Scope task config lookup to workspace folder

### LINKED ISSUE #2327: Error for debug python application in docker
Hi,

I write the `launch.json` file in my project
```

{
    "configurations": [
        {
            "name": "Docker: Python - Django",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}/app",
                        "remoteRoot": "/usr/src/app"
                    }
                ],
                "port": 8000,
                "projectType": "django",
                "django": true,
            },
        }
    ]
}
```
 With this `task.json`
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "docker-build",
            "label": "docker-build",
            "platform": "python",
            "dockerBuild": {
                "tag": "myapp:latest",
                "dockerfile": "${workspaceFolder}/app/Dockerfile",
                "context": "${workspaceFolder}",
                "pull": true
            }
        },
        {
            "type": "docker-run",
            "label": "docker-run: debug",
            "dependsOn": [
                "docker-build"
            ],
            "python": {
                "args": [
                    "runserver",
                    "0.0.0.0:8000"
                ],
                "file": "manage.py"
            },
            "dockerRun": {
                "ports": [
                    {
                        "hostPort": 8000,
                        "containerPort": 8000
                    }
                ],
                "volumes": [
                    {
                        "containerPath": "/usr/src/app",
                        "localPath": "${workspaceFolder}/app"
                    }
                ]
            }
        }
    ]
}
```
 The build works well without error and my container is up

After this build I get the message box error `Invalid message 'either "program", "module", or "code" must be specified'`

If I add "program", "module", or "code" attribut in `launch.json`, VSCode tell me that this key is not allowed.

What I miss ??

Thanks

Version: 1.49.0
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:20:50.359Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.19.0-10-amd64

### LINKED ISSUE #3641: Dockerrun task overwrites docker entry point with just python3 call not my app invokation
I followed a tutorial for Python in container running and debugging on VSCode from [here](https://code.visualstudio.com/docs/containers/quickstart-python). But the docker launch configuration that VSCode generates for me does not work. When I start it de launch config with F5 the container entry point is overwritten with a call to `python3` only. It does not start my app at all. Please advice, is that a bug in the docker extension?

See more details on my config below. It is all standard generated and not really modified. 
In terminal output you can see that it sets entry point to `python3`

Environment:
* Win11
* VSCode 1.72.2
* Docker extension 1.22.1

Auto generated files:
* `.vscode/tasks.json`
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "docker-build",
			"label": "docker-build",
			"platform": "python",
			"dockerBuild": {
				"tag": "exceltojson:latest",
				"dockerfile": "${workspaceFolder}/Dockerfile",
				"context": "${workspaceFolder}",
				"pull": true
			}
		},
		{
			"type": "docker-run",
			"label": "docker-run: debug",
			"dependsOn": [
				"docker-build"
			],
			"dockerRun": {
				"env": {
					"FLASK_APP": "app.py"
				}
			},
			"python": {
				"args": [
					"run",
					"--no-debugger",
					"--no-reload",
					"--host",
					"0.0.0.0",
					"--port",
					"5000"
				],
				"module": "flask"
			}
		}
	]
}
```
* `.vscode/launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Flask",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app.py",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "0"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true
        },
        {
            "name": "Docker: Python - Flask",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "python": {
                "pathMappings": [
                    {
                        "localRoot": "${workspaceFolder}",
                        "remoteRoot": "/app"
                    }
                ],
                "projectType": "flask"
            }
        }
    ]
}
```
* `Dockerfile`
```
# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim

EXPOSE 5000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY . /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
```

* Terminal output:
```
#11 writing image sha256:5f27eedb9f5e02e98a83e24cc30d3496381050d0a4fae0c5d9d2beeff6df78c4 0.0s done
#11 naming to docker.io/library/exceltojson:latest done
#11 DONE 0.2s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: docker-run: debug 

> docker run -dt -P --name "exceltojson-dev" -e "FLASK_APP=app.py" --label "com.microsoft.created-by=visual-studio-code" -v "c:\Users\JanKowalik\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy:/debugpy:ro,z" --entrypoint "python3" "exceltojson:latest" <

4f811149f9b42456a29b98a6c162bda450a8ba9cf9bf53ab076691fd9ddb6bfb
 *  Terminal will be reused by tasks, press any key to close it. 
```
* error dialog:
image

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #3641, fixes #2327

Tests:
- [x] In a workspace
    - [x] .NET
        - [x] Run
        - [x] Attach
    - [x] Node
        - [x] Run
        - [x] Attach
    - [x] Python
        - [x] Run
        - [x] Attach
- [x] In a workspace folder
    - [x] .NET
        - [x] Run
        - [x] Attach
    - [x] Node
        - [x] Run
        - [x] Attach
    - [x] Python
        - [x] Run
        - [x] Attach

### CODE REVIEW

File: src/tasks/TaskHelper.ts [hunk 1]
```diff
@@ -103,14 +103,14 @@ export function registerTaskProviders(ctx: ExtensionContext): void {
 }
 
 export function hasTask(taskLabel: string, folder: WorkspaceFolder): boolean {
-    const workspaceTasks = workspace.getConfiguration('tasks', folder.uri);
```
Comment (bwateratmsft) [inline src/tasks/TaskHelper.ts:106]: Now we can just pass the folder instead of `folder.uri`. Same as line 113 below.

**Review by karolz-ms — APPROVED** [review]
