### PR TITLE
Awareness toast for those only editing Dockerfiles

### LINKED ISSUE #1904: How can we make users more aware of the features this extension offers
Maybe provide links to docs/videos when new users edit Dockerfile and have not discovered other features?

### LINKED ISSUE #2005: Remove '...' for the "Docker Registries Help" and "Docker Contexts Help" commands
**OS:** All
**Build Version:** [20200520.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19784&view=results)

**Repro Steps:**
F1->Input Help->Check the Help commands for Docker Registries and Docker Contexts.

**Expect:**
There is no '...' for these two commands.

**Actual:**
There is '...' for these two commands.
image

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #1904, fixes #2005

### CODE REVIEW

File: src/telemetry/awarenessToast.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+ *--------------------------------------------------------------------------------------------*/
+
+import * as vscode from 'vscode';
+import { callWithTelemetryAndErrorHandling, IActionContext } from 'vscode-azureextensionui';
+import { ext } from '../extensionVariables';
+import { localize } from '../localize';
+
+const awarenessToastShownKey = 'vscode-docker.awarenessToast.shown';
+
+// TODO: text and link
```
Comment (bwateratmsft) [inline src/telemetry/awarenessToast.ts:13]: Do
