### PR TITLE
Run most commands without a shell

### LINKED ISSUE #3725: `Failed to set up event listener: Unexpected token W in JSON at position 0` error
Originally from https://github.com/microsoft/vscode-docker/issues/3724#issuecomment-1330889789

/cc @brainz80

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #3725 either mostly or entirely. There are still scenarios where we will run in a shell; some of these can't plausibly be avoided. For example, because tasks support the `customOptions` argument which is a single string, but could contain multiple arguments that can't easily be separated, it is still necessary to run those through a shell. However, the output is never parsed for those, so I think that everything should work fine.

### CODE REVIEW

File: src/extensionVariables.ts [hunk 1]
```diff
@@ -59,8 +59,6 @@ export namespace ext {
     // Container runtime related items
     export let runtimeManager: ContainerRuntimeManager;
     export let orchestratorManager: OrchestratorRuntimeManager;
-    export const runWithDefaultShell = runWithDefaultShellInternal;
-    export const streamWithDefaultShell = streamWithDefaultShellInternal;
-    export const runOrchestratorWithDefaultShell = runOrchestratorWithDefaultShellInternal;
```
Comment (bwateratmsft) [inline src/extensionVariables.ts:64]: The orchestrator ones weren't actually being used, so I opted to just remove them. If we need them in the future they can be added back.

File: src/runtimes/docker/clients/DockerClientBase/DockerListNetworkRecord.ts [hunk 2]
```diff
@@ -1,79 +1,79 @@
-/*---------------------------------------------------------------------------------------------
```
Comment (bwateratmsft) [inline src/runtimes/docker/clients/DockerClientBase/DockerListNetworkRecord.ts:1]: Git wants to change the line endings. No idea why, but it's going to keep trying to do it, so may as well just check it in.

File: src/runtimes/docker/clients/DockerClientBase/parseDockerLikeEnvironmentVariables.ts [hunk 3]
```diff
@@ -1,26 +1,26 @@
-/*---------------------------------------------------------------------------------------------
```
Comment (bwateratmsft) [inline src/runtimes/docker/clients/DockerClientBase/parseDockerLikeEnvironmentVariables.ts:1]: Git wants to change the line endings. No idea why, but it's going to keep trying to do it, so may as well just check it in.

File: src/runtimes/docker/utils/dayjs.ts [hunk 4]
```diff
@@ -1,54 +1,54 @@
-/*---------------------------------------------------------------------------------------------
```
Comment (bwateratmsft) [inline src/runtimes/docker/utils/dayjs.ts:1]: Git wants to change the line endings. No idea why, but it's going to keep trying to do it, so may as well just check it in.

**Review by karolz-ms — DISMISSED** [review]
Looks good, just one question

File: src/runtimes/docker/commandRunners/wslStream.ts [hunk 5]
```diff
@@ -22,20 +22,14 @@ export type WslShellCommandRunnerOptions = ShellStreamCommandRunnerOptions & {
...
         const command = this.options.wslPath ?? 'wsl.exe';
-        const args = [
-            ...(this.options.distro ? ['-d', this.options.distro] : []),
-            '--',
-            commandResponse.command,
-            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
-            ...Shell.getShellOrDefault(this.options.shellProvider).quote(commandResponse.args),
-        ];
+        const args = composeArgs(
+            withNamedArg('-d', this.options.distro),
```
[the remark this answers is not in the document]
Comment (bwateratmsft) [reply src/runtimes/docker/commandRunners/wslStream.ts:28]: IIRC, the `withNamedArg()` function will internally noop if distro is absent.

[the remark this answers is not in the document]
Comment (bwateratmsft) [reply src/runtimes/docker/commandRunners/wslStream.ts:28]: Yes, double-checked and that is indeed the behavior: https://github.com/microsoft/vscode-docker-extensibility/blob/main/packages/container-runtimes/src/utils/commandLineBuilder.ts#L99

[the remark this answers is not in the document]
Comment (karolz-ms) [reply src/runtimes/docker/commandRunners/wslStream.ts:28]: cool

File: src/runtimes/runners/runWithDefaults.ts [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+
+export function streamWithDefaultsInternal<T>(callback: StreamingClientCallback<IContainersClient, T>, additionalOptions?: DefaultEnvStreamCommandRunnerOptions): AsyncGenerator<T> {
+    return streamWithDefaults(
+        callback,
+        ext.runtimeManager,
+        additionalOptions
+    );
+}
+
+async function runWithDefaults<TClient extends ClientIdentity, T>(
```
Comment (danegsta) [inline src/runtimes/runners/runWithDefaults.ts:37]: It might be worth defining the method overloads so the type system can properly determine the expected return type based on the value of callback:
```
function runWithDefaults<TClient extends ClientIdentity, T>(callback: ClientCallback<TClient, T>, runtimeManager: RuntimeManager<TClient>, additionalOptions?: DefaultEnvStreamCommandRunnerOptions): Promise<T>;
function runWithDefaults<TClient extends ClientIdentity>(callback: VoidClientCallback<TClient>, runtimeManager: RuntimeManager<TClient>, additionalOptions?: DefaultEnvStreamCommandRunnerOptions): Promise<void>;
async function runWithDefaults<TClient extends ClientIdentity, T>(callback: ClientCallback<TClient, T> | VoidClientCallback<TClient>, runtimeManager: RuntimeManager<TClient>, additionalOptions?: DefaultEnvStreamCommandRunnerOptions): Promise<T | void> { ...
```

Comment (bwateratmsft) [reply src/runtimes/runners/runWithDefaults.ts:37]: The definitions of the `runWithDefaultsInternal` / `streamWithDefaultsInternal` accomplish that

Comment (danegsta) [reply src/runtimes/runners/runWithDefaults.ts:37]: So they do; should the names of runWithDefaults and runWithDefaultsInternal be swapped? I feel like the current naming is a bit confusing.

Comment (bwateratmsft) [reply src/runtimes/runners/runWithDefaults.ts:37]: I think that's reasonable.

**Review by danegsta — APPROVED** [review]
