### PR TITLE
Force refresh of Docker context after 10 seconds

### LINKED ISSUE #2383: [Codespaces] The context keeps "Switching" state after using a different one
**OS:** Windows 10
**Build Version:** 20201009.1

**Repro Steps:**
1. Create a Linux Codespace and connect it.
2. Install Docker extension in this Codespace.
3. Create a new context.
4. Use this new context and check the result.

**Expect:**
Switch to the new context successfully.

**Actual:**
The context keeps "Switching" state after using a different one.
image

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2383

### CODE REVIEW

File: src/commands/context/useDockerContext.ts [hunk 1]
```diff
@@ -30,8 +30,20 @@ export async function useDockerContext(actionContext: IActionContext, node?: Con
...
+                        clearTimeout(timer);
+
                         resolve();
                     });
+
+                    // If 10 seconds pass and it hasn't been updated, force a refresh
+                    // This covers the scenario where the filesystem watchers aren't working (e.g. Codespaces)
+                    const timer = setTimeout(() => {
+                        disposable.dispose();
+                        clearTimeout(timer);
```
Comment (karolz-ms) [inline src/commands/context/useDockerContext.ts:42]: Do we need the call to `clearTimeout` here (when we are already executing the timeout function)?

**Review by karolz-ms — APPROVED** [review]
Just one small question.

BTW, I noticed that we call this command in the "deploy to ACI" scenario, so this change takes care of that too, nice

File: src/commands/context/useDockerContext.ts (hunk 1 above)
Comment (bwateratmsft) [reply src/commands/context/useDockerContext.ts:42]: I suppose not; I was conflating it with `setInterval` which loops by default.
