### PR TITLE
Improve build-image and fix some strict typescript issues 

### LINKED ISSUE #377: Don't prompt for Dockerfile if only one in project (command palette->Build Image)

### PR DESCRIPTION
**Pull request by StephenWeatherford**
fixes #377

### CODE REVIEW

File: commands/build-image.ts [hunk 1]
```diff
@@ -72,27 +74,33 @@ export async function buildImage(dockerFileUri?: vscode.Uri): Promise<void> {
...
-    if (!uri) { return; }
+    while (!dockerFileItem) {
+        let resolvedItem: Item | undefined = await resolveImageItem(workspaceFolder, dockerFileUri);
+        if (resolvedItem) {
+            dockerFileItem = resolvedItem;
+        } else {
+            let msg = "Couldn't find a Dockerfile in your workspace. Would you like to add Docker files to the workspace?";
+            let response = await ext.ui.showWarningMessage(msg, DialogResponses.yes, DialogResponses.no);
+            if (response === DialogResponses.no) {
+                actionContext.properties.cancelStep = msg;
```
Comment (EricJizbaMSFT) [inline commands/build-image.ts]: Users can also cancel the dialog by clicking the 'x' icon on the notification, so your 'cancelStep' telemetry here won't be entirely accurate. You could use a try/catch or you could do something like this to fix that: https://github.com/Microsoft/vscode-azureappservice/blob/e9046407094fedbb77d994c4125b2d2bfa5819b8/src/util.ts#L63

File: commands/build-image.ts [hunk 2]
```diff
@@ -72,27 +74,33 @@ export async function buildImage(dockerFileUri?: vscode.Uri): Promise<void> {
...
 
-    let contextPath: string = uri.path;
+    let contextPath: string = dockerFileItem.folderPath;
     if (defaultContextPath && defaultContextPath !== '') {
         contextPath = defaultContextPath;
     }
 
+    // Get imageName based on name of subfolder containing the Dockerfile, or else workspacefolder
     let imageName: string;
-    if (process.platform === 'win32') {
```
Comment (EricJizbaMSFT) [inline commands/build-image.ts]: omg thank you for fixing this to use `path.basename` - looks so much cleaner 😂

File: dockerExtension.ts [hunk 3]
```diff
@@ -165,26 +165,23 @@ export async function activate(ctx: vscode.ExtensionContext): Promise<void> {
...
-    return client.stop();
+    return await client.stop();
 }
 
 namespace Configuration {
 
     let configurationListener: vscode.Disposable;
 
     export function computeConfiguration(params: ConfigurationParams): vscode.WorkspaceConfiguration[] {
-        if (!params.items) {
```
Comment (EricJizbaMSFT) [inline dockerExtension.ts]: Don't quite understand what this check was doing. It's safe to remove now?

File: commands/build-image.ts [hunk 4]
```diff
@@ -1,69 +1,71 @@
...
 }
 
 function createItem(folder: vscode.WorkspaceFolder, uri: vscode.Uri): Item {
     let filePath = path.join(".", uri.fsPath.substr(folder.uri.fsPath.length));
 
     return <Item>{
-        description: null,
-        file: filePath,
+        description: undefined,
+        fileName: filePath,
```
[the remark this answers is not in the document]
Comment (StephenWeatherford) [reply commands/build-image.ts]: Fixed. filePath

File: commands/build-image.ts [hunk 5]
```diff
@@ -1,69 +1,71 @@
...
     };
 }
 
-function computeItems(folder: vscode.WorkspaceFolder, uris: vscode.Uri[]): vscode.QuickPickItem[] {
-    let items: vscode.QuickPickItem[] = [];
-    // tslint:disable-next-line:prefer-for-of // Grandfathered in
-    for (let i = 0; i < uris.length; i++) {
-        items.push(createItem(folder, uris[i]));
-    }
+function createItems(folder: vscode.WorkspaceFolder, uris: vscode.Uri[]): Item[] {
```
[the remark this answers is not in the document]
Comment (StephenWeatherford) [reply commands/build-image.ts]: Done

File: commands/build-image.ts (hunk 1 above)
Comment (StephenWeatherford) [reply commands/build-image.ts]: Thanks for catching.  Changed to this for now:

            let msg = "Couldn't find a Dockerfile in your workspace. Would you like to add Docker files to the workspace?";
            actionContext.properties.cancelStep = msg;
            await ext.ui.showWarningMessage(msg, DialogResponses.yes, DialogResponses.cancel);
            actionContext.properties.cancelStep = undefined;
            await vscode.commands.executeCommand('vscode-docker.configure');
            // Try again

File: commands/build-image.ts (hunk 2 above)
Comment (StephenWeatherford) [reply commands/build-image.ts]: :-)

File: dockerExtension.ts (hunk 3 above)
Comment (StephenWeatherford) [reply dockerExtension.ts]: Now it returns [] instead of undefined, which is what the signature says. Also signature says params should never be undefined (as pass to us by vscode). AFAIK this is correct.
