### PR TITLE
chmod +x the GetVsDbg.sh script

### LINKED ISSUE #2453: Error: /bin/sh: 1: /home/user/.vsdbg/getvsdbg.sh: Permission denied
This is the  permissions of my debug file 
drwxrwxr-x  2 user user 4096 okt 30 14:56 .vsdbg

Does this occur consistently? Yes 

Action: docker-attach
Error type: 126
Error Message: Process '/home/user/.vsdbg/getvsdbg.sh -v latest -r linux-x...' exited with code 126
Error: /bin/sh: 1: /home/user/.vsdbg/getvsdbg.sh: Permission denied

Version: 1.7.0
OS: linux
OS Release: 5.4.0-52-generic
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
ChildProcess.<anonymous> extension.bundle.js:46:91411
ChildProcess.emit events.js:223:5
maybeClose child_process.js:1021:16
Socket.<anonymous> child_process.js:430:11
Socket.emit events.js:223:5
Pipe.<anonymous> net.js:664:12
```

</details>

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2453

### CODE REVIEW

File: src/debugging/netcore/VsDbgHelper.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ const acquisition: { url: string, scriptPath: string, getShellCommand(runtime: V
             url: 'https://aka.ms/getvsdbgsh',
             scriptPath: path.join(vsDbgInstallBasePath, 'getvsdbg.sh'),
             getShellCommand: (runtime: VsDbgRuntime, version: VsDbgVersion) => {
-                return `${acquisition.scriptPath} -v ${version} -r ${runtime} -l "${getInstallDirectory(runtime, version)}"`;
+                return `chmod +x ${acquisition.scriptPath} && ${acquisition.scriptPath} -v ${version} -r ${runtime} -l "${getInstallDirectory(runtime, version)}"`;
```
Comment (philliphoff) [inline src/debugging/netcore/VsDbgHelper.ts:37]: Should `${acquisition.scriptPath}` be quoted (like we do for the installation directory)?

**Review by philliphoff — APPROVED** [review]

File: src/debugging/netcore/VsDbgHelper.ts (hunk 1 above)
Comment (bwateratmsft) [reply src/debugging/netcore/VsDbgHelper.ts:37]: Yes, good catch.
