### PR TITLE
ACR Fixes (Logs & Docker Pull)

### LINKED ISSUE #639: Unhandled error if you cancel saving Azure log
1) On ACR node -> View Azure Logs
2) Open a build and click on the copy log icon
image
3) Cancel the save dialog

!) Error 'TypeError': Cannot read property 'fsPath' of undefined

TWO PROBLEMS:
1) The error doesn't have the "Report An Issue" button - should wrap the call in CallWithTelemtryAndErrorHandling
2) the error itself

### LINKED ISSUE #640: Save Azure log dialog shows "log..log" as the filename extension
(On a Mac)
1) On ACR node -> View Azure Logs
2) Open a build and click on the copy log icon
image
!) The Save As field shows "ccb.log..log" as the filename

### LINKED ISSUE #648: docker.acr.pullimage issue
Repro steps:

Tried to pull bitnami/java image from Azure

Action: vscode-docker.acr.pullImage
Error type: TypeError
Error Message: Path must be a string. Received undefined

Version: 0.4.0
OS: darwin

image

### LINKED ISSUE #666: Error when pushing image to ACR
Repro steps:
Running through the Docker: ACR Tasks: Build Image in VS Code
Error is generated when trying to push image to Azure

Action: vscode-docker.acr.quickBuild
Error type: SourceLocationNotFound
Error Message: The provided source location 'source/201811290000/20791c20-86a1-41c6-ae5c-07b8473fe461.tar.gz' is invalid or doesn't exists. Please use 'GetBuildSourceUploadUrl' to get a valid location to upload the source.

Version: 0.4.0
OS: win32

### PR DESCRIPTION
**Pull request by rosanch**
This closes #639, closes #640, closes #648, and closes #666 

	Unhandled error if you cancel saving Azure log #639
	Save Azure log dialog shows "log..log" as the filename extension #640
	docker.acr.pullimage issue #648

### CODE REVIEW

File: commands/azureCommands/pull-from-azure.ts [hunk 1]
```diff
@@ -71,7 +70,7 @@ async function pullImage(loginServer: string, imageRequest: string, username: st
                 // Temporary work-around for this error- same as Azure CLI
                 // See https://github.com/Azure/azure-cli/issues/4843
                 ext.outputChannel.show();
-                reject(new Error(`In order to log in to the Docker CLI using tokens, you currently need to go to \n${dockerConfigPath} and remove "credsStore": "wincred" from the config.json file, then try again. \nDoing this will disable wincred and cause Docker to store credentials directly in the .docker/config.json file. All registries that are currently logged in will be effectly logged out.`));
+                reject(new Error(`In order to log in to the Docker CLI using tokens, you currently need to go to \nOpen your Docker config file and remove "credsStore": "wincred" from the config.json file, then try again. \nDoing this will disable wincred and cause Docker to store credentials directly in the .docker/config.json file. All registries that are currently logged in will be effectly logged out.`));
```
Comment (StephenWeatherford) [inline commands/azureCommands/pull-from-azure.ts]: Why not point them directly to the config path like before?

File: commands/azureCommands/acr-logs-utils/tableViewManager.ts [hunk 2]
```diff
@@ -31,20 +31,18 @@ export class LogTableWebview {
...
+                    })
+                );
             } else if (message.copyRequest) {
                 // tslint:disable-next-line:no-unsafe-any
                 clipboardy.writeSync(message.copyRequest.text);
-
+                vscode.window.showInformationMessage("The digest was successfully copied to the clipboard.");
             } else if (message.loadMore) {
                 const alreadyLoaded = this.logData.logs.length;
                 await this.logData.loadLogs({
```
Comment (StephenWeatherford) [inline commands/azureCommands/acr-logs-utils/tableViewManager.ts]: Can logLogs fail and would you want to show an error message?  If so, you should do the same here, etc.

File: commands/azureCommands/pull-from-azure.ts (hunk 1 above)
Comment (rosanch) [reply commands/azureCommands/pull-from-azure.ts]: Because they can have an especial config, and that folder could not be in the default path.
So I didn't think it wasn't worth the trouble to look for the folder for a message that is there for a workaround that shouldn't be needed anymore. 
I was going to remove it all together but left it just as a precaution.

File: commands/azureCommands/acr-logs-utils/tableViewManager.ts (hunk 2 above)
Comment (rosanch) [reply commands/azureCommands/acr-logs-utils/tableViewManager.ts]: I'll add telemetry to the whole function then.

Comment (StephenWeatherford) [reply commands/azureCommands/acr-logs-utils/tableViewManager.ts]: You could, but the telemetry on errors and usage will be less accurate that way.

Comment (StephenWeatherford) [reply commands/azureCommands/acr-logs-utils/tableViewManager.ts]: I'd suggest adding message to the telemetry so we can what usage/errors are referring to.
 
```
            await callWithTelemetryAndErrorHandling( 
                'ACR-logsTableListeners', 
                async function (this: IActionContext) => { 
                    this.properties.message = message;
                    ...

Comment (rosanch) [reply commands/azureCommands/acr-logs-utils/tableViewManager.ts]: Ok, I think I got it right this time.
