### PR TITLE
Fix platform check

### LINKED ISSUE #1838: The "Install Docker" command on Mac opens the Linux install page, instead of installing

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #1838

### CODE REVIEW

File: src/commands/installDocker.ts [hunk 1]
```diff
@@ -3,20 +3,17 @@
...
-import LocalOSProvider from '../utils/LocalOSProvider';
 import { openExternal } from '../utils/openExternal';
 import { MacDockerInstaller, WindowsDockerInstaller } from './dockerInstaller';
 
 export async function installDocker(context: IActionContext): Promise<void> {
-    const osProvider = new LocalOSProvider();
-    if (osProvider.os === 'Linux') {
-        // eslint-disable-next-line @typescript-eslint/tslint/config
-        await openExternal('https://aka.ms/download-docker-linux-vscode');
+    if (os.platform() === 'win32') {
```
Comment (ravipal) [inline src/commands/installDocker.ts:12]: The root cause was osProvider.os is returning the wrong value. We care about just 3 OSes. Can the osProvider.os be updated to return one of (Windows, Linux, Mac)

Comment (bwateratmsft) [reply src/commands/installDocker.ts:12]: Not without spending the time evaluating every single call to `osProvider.os`. Additionally, it's headed for deprecation. `os.platform()` is better.

Comment (ravipal) [reply src/commands/installDocker.ts:12]: Why not basically port the same logic that you have here to `osProvider.os`, so all caller don't have to come up with the same login in their code. We have about 8 calls using `osProvider.os` and if this returns the right value, then it shouldn't be an issue. Also we can get rid of osProvider.isMac.

Comment (bwateratmsft) [reply src/commands/installDocker.ts:12]: Again--we would have to evaluate every single call to `osProvider.os` to see how it would affect them. Now isn't the time to do that.

Comment (ravipal) [reply src/commands/installDocker.ts:12]: os.platform() returns one of 9 values and the caller needs to reduce it to 3. IMO osProvider.os is a good utility function that reduce it to the 3 values that we are interested in.

Comment (bwateratmsft) [reply src/commands/installDocker.ts:12]: By all means then, update it everywhere, but make sure you aren't regressing any other features by the change. IMO it's the wrong move right now and I'm not willing to do it.

Comment (ravipal) [reply src/commands/installDocker.ts:12]: Fair enough. I will make that change later.
