### PR TITLE
Fix some "shell" quoting bugs

### LINKED ISSUE #3758: The "copy debugger" notification still pops up when running 'Docker .Net Core Attach (Preview)' configuration again
**OS:** All
**Build Version:** 20221206.1
**Regression:** Previous Release

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code -->
 F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
3. Right click the docker-compose.yml --> Select "Compose Up".
4. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
5. Run the above configuration, select the running container from step4 and click **yes** in the below notification to copy the debugger on the container.
image
6. Stop debugging.
7. Debug again and select the running container.
8. Check there shouldn't be any "copy debugger" notification.

**Expect:**
There shouldn't be any "copy debugger" notification.

**Actual:**
The "copy debugger" notification pops up again.
image

**More Info:**
This issue does not reproduce on the previous released Docker extension 1.23.1.

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #3758. Creating as draft since the upstream PR isn't merged yet.

Things to test:
- [x] Windows
    - [x] Container list and inspect
    - [x] Image list and inspect
    - [x] Network list and inspect
    - [x] Volume list and inspect
    - [x] Context list and inspect
    - [x] .NET debug attach
    - [x] .NET debug w/ SSL
    - [x] Files view
        - [x] Windows container #3761
        - [x] Linux container
    - [x] Container actions (start, stop, remove, prune, etc.)
    - [x] Compose subset
    - [x] Unrelated container tooltip change
- [x] Unix
    - [x] Container list and inspect
    - [x] Image list and inspect
    - [x] Network list and inspect
    - [x] Volume list and inspect
    - [x] Context list and inspect
    - [x] .NET debug attach
    - [x] .NET debug w/ SSL
    - [x] Files view
        - [x] Linux container
    - [x] Container actions (start, stop, remove, prune, etc.)
    - [x] Compose subset
    - [x] Unrelated container tooltip change

### CODE REVIEW

File: src/tree/containers/ContainerTreeItem.ts [hunk 1]
```diff
@@ -169,7 +169,7 @@ const containerTooltipTemplate = `
 ---
 
 #### Image
-{{ imageName }} ({{ substr imageId 7 12 }})
+{{ image.originalName }} ({{ substr imageId 7 12 }})
```
Comment (bwateratmsft) [inline src/tree/containers/ContainerTreeItem.ts:172]: Not related to this bug/PR, but this and the line below are some super easy fixes for some tooltip issues in the Containers view. Figured it was easier to just fix them than to create an issue, triage, etc. etc.

**Review by karolz-ms — APPROVED** [review]

**Review by danegsta — APPROVED** [review]
