### PR TITLE
Fix image refresh

### LINKED ISSUE #371: Images list does not refresh after tagging an image
Repros in 0.1.0

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #371 

The old code only compared images, but we also need to compare tags, and might as well compare everything for better reliability.

### CODE REVIEW

File: explorer/models/rootNode.ts [hunk 1]
```diff
@@ -67,34 +67,24 @@ export class RootNode extends NodeBase {
...
-                            needToRefresh = true;
-                            break
-                        }
-                    }
-                }
-
-                if (needToRefresh) {
+                let imagesAsJson = JSON.stringify(images);
+                let cacheAsJson = JSON.stringify(this._imageCache);
+                if (imagesAsJson !== cacheAsJson) {
```
Comment (PrashanthCorp) [inline explorer/models/rootNode.ts]: Would you also need to sort `this._imageCache` ?

Comment (StephenWeatherford) [reply explorer/models/rootNode.ts]: It comes directly from images, which is being sorted here.  Changed it to _sortedImageCache to make that clear.
