### PR TITLE
Unconditionally install VSDBG for .NET launch configs

### LINKED ISSUE #2233: Fail to run 'Docker .Net Core Attach (Preview)' configuration which using docker-compose.debug.yml to compose-up
**OS:** Ubuntu 18.04
**Build Version:** 20200807.6
**.NET Core SDK:** 3.1.302

**Repro Steps:**
1. Create a .NET Core MVC project by "dotnet new mvc --no-https".
2. Open the project in VS Code --> Prompt to add the required assets --> Yes
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files.
4. Right click the docker-compose.debug.yml --> Select "Compose Up".
5. Open launch.json and click 'Add Configration…', and choose 'Docker .NET Core Attach (Preview)'.
6. Run the above configuration, select the running container from step4.

**Expect:**
It will not prompt to copy the debugger to the container, and run the configuration successfully without any error.

**Actual:**
It prompts a dialog to copy the debugger to the container. Click "Yes" to allow copying vsdbg to the container, an error "The pipe program 'docker' exited unexpectedly with code 126" occurs.
image
image

**More Info:**
1. This issue does not reproduce on Windows and Mac.
2. This issue does not reproduce if execute "Compose Up" command for docker-compose.yml.

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2233

Also some other improvements to the debugger installation experience, and increased robustness.

### CODE REVIEW

File: src/debugging/netcore/NetCoreDebugHelper.ts [hunk 1]
```diff
@@ -197,12 +198,19 @@ export class NetCoreDebugHelper implements DebugHelper {
...
-        if (platformOS === 'Windows') {
-            await installDebuggerIfNecessary('win7-x64', 'latest');
-        } else {
-            await installDebuggerIfNecessary('linux-x64', 'latest');
-            await installDebuggerIfNecessary('linux-musl-x64', 'latest');
-        }
+        await window.withProgress(
+            {
+                location: ProgressLocation.Notification,
+                title: localize('vscode-docker.debug.netcore.acquiringDebuggers', 'Acquiring VSDBG...'),
```
Comment (karolz-ms) [inline src/debugging/netcore/NetCoreDebugHelper.ts:204]: "Installing debugger into the container..." maybe?

Not sure if everybody knows what "VSDBG" is...

**Review by karolz-ms — APPROVED** [review]

File: src/debugging/netcore/NetCoreDebugHelper.ts (hunk 1 above)
Comment (bwateratmsft) [reply src/debugging/netcore/NetCoreDebugHelper.ts:204]: In this it's installing locally, but I agree about the name change. I'll do "Acquiring .NET debugger..."
