### PR TITLE
Run interactive not working if no exposed ports

### LINKED ISSUE #482: 'Run Interactive'/'Run' doesn't work for "hello-world:latest" image
**Repro Steps**:
1. Run 'docker run hello-world' command -> Make sure the 'hello-world: latest' displays under Images node.  
2. Right click 'hello-world: latest' -> Execute 'Run Interactive'.
3. Check the result.

**Expect**:
 'Run Interactive'/'Run' works well for "hello-world:latest"

**Actual**:
 'Run Interactive'/'Run' doesn't work for "hello-world:latest".

**More Info:**
1. This issue doesn't reproduce on the previous release docker extension 0.2.0.
2. 'Run Interactive'/'Run' works well for "registry" image.

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #482 

Check for data.Config.ExposedPorts = undefined

### CODE REVIEW

File: commands/start-container.ts [hunk 1]
```diff
@@ -41,29 +39,23 @@ export async function startContainerCore(actionContext: IActionContext, context:
...
-            if (ports.length) {
-                const portMappings = ports.map((port) => `-p ${port.split("/")[0]}:${port}`); //'port' is of the form number/protocol, eg. 8080/udp.
-                // In the command, the host port has just the number (mentioned in the EXPOSE step), while the destination port can specify the protocol too
-                options += ` ${portMappings.join(' ')}`;
-            }
+        let ports: string[] = [];
+        try {
+            ports = await docker.getExposedPorts(imageToStart.Id);
+        } catch (error) {
+            vscode.window.showWarningMessage(`Unable to retrieve exposed ports: ${parseError(error).message}`);
```
Comment (EricJizbaMSFT) [inline commands/start-container.ts]: So you're intentionally letting the user continue here, correct? That's why it's just `showWarningMessage` without an `await`?

Comment (StephenWeatherford) [reply commands/start-container.ts]: Yes.  Mixed feelings about this, though.
