### PR TITLE
Remove ansi escape characters

### LINKED ISSUE #1511: Hard to read the output logs after executing "Run as task in Azure" action for "taskmulti.yaml"
**OS:** All
**Build Version:** [20191221.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13288&view=results)
**Regression:** Not a Regression

**Steps to reproduce:**

1. Download the [acr-build-helloworld-node](https://github.com/Azure-Samples/acr-build-helloworld-node) project.
2. Open this project in VS Code.
3. Right click the "taskmulti.yaml" file and execute "Run as task in Azure".
4. Check the output logs.

**Expect:**
Easy to read the output logs.

**Actual:**
Hard to read the output logs after executing "Run as task in Azure" action.
image

### PR DESCRIPTION
**Pull request by ravipal**
Remove ansi escape sequence characters.
Fixes #1511

### CODE REVIEW

File: src/utils/azureUtils.ts [hunk 1]
```diff
@@ -163,6 +164,17 @@ export async function streamLogs(node: AzureRegistryTreeItem, run: AcrModels.Run
     );
 }
 
+function removeAnsiEscapeSequences(text: string): string {
+    // (^.*\x1B\[\d*;?\d*H)     - Esc[Line;ColumnH represents the cursor position. Remove any string before setting the cursore position.
```
Comment (karolz-ms) [inline src/utils/azureUtils.ts]: Is the first series of digits mandatory? In other words, is it OK if this regex matches 'Esc[H' (no digits)?

Comment (karolz-ms) [reply src/utils/azureUtils.ts]: In other words, should the first sequence of digits be matched by '\d+'?

Comment (ravipal) [reply src/utils/azureUtils.ts]: The documentation says below. So I the digits are optional. I will leave it as d*. Also this is the same regx used in Container Tools Window and so far it is working fine.
'Cursor Position:
Moves the cursor to the specified position (coordinates).
If you do not specify a position, the cursor moves to the home position at the upper-left corner of the screen (line 0, column 0).'

---
In reply to: [398217974](https://github.com/microsoft/vscode-docker/pull/1789#discussion_r398217974) [](ancestors = 398217974)
