### PR TITLE
Fixes hovering colors over the digest, and minor typos.

### LINKED ISSUE #662: Hard to see the digest when hovering on it in Logs window
**OS**: Win10 / Mac
**Node.js**: V10.13.0
**Build Definition**: [20181128.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=963)

**Repro Steps:**
1. Create a build task(please refer to below link:
image
2. Run a task.
3. View Azure logs.
4. In Logs window, hover on the digest.

**Expect:**
Easy to see the entire digest.

**Actual:**
Hard to see the digest.
image

### PR DESCRIPTION
**Pull request by rosanch**
Fixes #662

### CODE REVIEW

**Comment by rosanch** [comment]
Fixes #775 
Fixes #772 
Added to the PR

File: commands/azureCommands/delete-image.ts [hunk 1]
```diff
@@ -36,7 +36,7 @@ export async function untagAzureImage(context?: AzureImageTagNode): Promise<void
     const shouldDelete = await ext.ui.showWarningMessage(
         `Are you sure you want to untag '${image.toString()}'? This does not delete the manifest referenced by the tag.`,
         { modal: true },
-        DialogResponses.deleteResponse,
+        { title: "Untag" },
         DialogResponses.cancel);
 
     if (shouldDelete === DialogResponses.deleteResponse) {
```
Comment (StephenWeatherford) [inline commands/azureCommands/delete-image.ts]: That ain't gonna work - you're comparing the result to deleteResponse.  Preferred pattern:

const untag = { title: "Untag" };
const shouldUntag = await ext.ui.showWarningMessage(
…
        untag, 
...
);

      if (shouldDelete === untag) {

Comment (rosanch) [reply commands/azureCommands/delete-image.ts]: Sorry about that one. 
Fixed
