### PR TITLE
Change default bash command for attaching the shell in Linux container

### LINKED ISSUE #518: Fail to 'Attach Shell' for 'registry' with error
Repro Steps:
1. Run 'docker run registry'.
2. Navigate to 'Containers' node -> Right click the 'registry' container ->Select 'Attach Shell'.
3. Check the result.

Expect:
Succeed to execute 'Attach Shell' fro container 'registry'.

Actual:
Fail to Fail to 'Attach Shell' for 'registry' with error.
compare

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #518

Powershell: 
image

CMD: 
image

 Bash on Mac: 
image

### CODE REVIEW

File: commands/open-shell-container.ts [hunk 1]
```diff
@@ -17,7 +16,7 @@ function getEngineTypeShellCommands(engineType: DockerEngineType): string {
     const configOptions: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration('docker');
     switch (engineType) {
         case DockerEngineType.Linux:
-            return configOptions.get('attachShellCommand.linuxContainer', '/bin/sh');
+            return configOptions.get('attachShellCommand.linuxContainer', '/bin/sh -c "[ -e /bin/bash ] && /bin/bash || /bin/sh"');
```
Comment (StephenWeatherford) [inline commands/open-shell-container.ts]: This is totally unnecessary, could you remove the default here?  Thanks.

Comment (PrashanthCorp) [reply commands/open-shell-container.ts]: I just realized that changing the setting to blank would still not pick up this default. Thanks for the heads up.

Comment (PrashanthCorp) [reply commands/open-shell-container.ts]: Should I remove the `powershell`  default too below?
