### PR TITLE
Have `ContextLoadingClient` listen for any end-of-loading event

### LINKED ISSUE #3132: Docker view keeps loading without any notification if there is no Docker Desktop installed
**OS:** Win 10
**Build Version:** 20210809.1
**Regression:** Previous Release

**Repro Steps:**
1. Make sure there is **no Docker Desktop** on the machine.
2. Install the Docker extension in VS Code.
3. Open the Docker view.
4. Check whether a notification pops up to remind user to install Docker Desktop.

**Expect:**
A notification pops up to remind user to install Docker Desktop.
expect

**Actual:**
Docker view keeps loading without any notification.
testactual

**More Info:**
1. This notification pops up after expanding the Networks/Volumes/Contexts view.
2. This issue does not reproduce on the previous released Docker extension 1.15.0.

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #3132. Pending calls through `ContextLoadingClient` will reject with the same error context loading failed with, if it fails.

### CODE REVIEW

File: src/docker/ContextLoadingClient/ContextLoadingClient.ts [hunk 1]
```diff
@@ -22,10 +21,15 @@ import { DockerVolume, DockerVolumeInspection } from '../Volumes';
 export class ContextLoadingClient implements DockerApiClient {
     private readonly contextLoadingPromise: Promise<void>;
 
-    public constructor(ctxMgr: ContextManager) {
-        this.contextLoadingPromise = new Promise((resolve) => {
-            const disposable = ctxMgr.onContextChanged(() => {
+    public constructor(onFinishedLoading: Event<unknown | undefined>) {
+        this.contextLoadingPromise = new Promise((resolve, reject) => {
+            const disposable = onFinishedLoading((result) => {
```
Comment (karolz-ms) [inline src/docker/ContextLoadingClient/ContextLoadingClient.ts:26]: Name this parameter `error` (because it is that)

**Review by karolz-ms — APPROVED** [review]
