### PR TITLE
ACR Fixes 

### LINKED ISSUE #650: ACR Build for Dockerfile fails through extension
Issue Type: <b>Bug</b>

Repro files located here - `https://github.com/sajayantony/dockerfiles/tree/master/arm`

```
The following dependencies were found:
- image:
    registry: sajaywcus.azurecr.io
    repository: curl
    tag: da2p
    digest: sha256:666b7069d7007140de69d256fa58846328cc0cc025fd5afa297a54f6571b955b
  runtime-dependency:
    registry: registry.hub.docker.com
    repository: library/alpine
    tag: latest
    digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
  git: {}

2018/11/26 22:35:25 Successfully populated digests for step ID: build
2018/11/26 22:35:25 Step ID: push marked as successful (elapsed time in seconds: 31.557586)

Run ID: da2p was successful after 49s
Setting up temp file with 'sourceArchive567990.tar.gz'
   Sending source code to temp file
   Getting build source upload URL 
   Getting blob info from upload URL 
   Creating blob service 
   Creating block blob 
Uploaded source code to /var/folders/y0/b2l3cygn1zx6mc86qklppwx80000gn/sourceArchive567990.tar.gz
Set up run request
Scheduled run da2q
2018/11/26 22:36:30 Using acb_vol_b7e1045e-705a-4cd9-9375-48de0b52a35b as the home volume
2018/11/26 22:36:30 Setting up Docker configuration...
2018/11/26 22:36:31 Successfully set up Docker configuration
2018/11/26 22:36:31 Logging in to registry: sajaywcus.azurecr.io
2018/11/26 22:36:33 Successfully logged in
2018/11/26 22:36:33 Executing step ID: build. Working directory: '', Network: ''
2018/11/26 22:36:33 Obtaining source code and scanning for dependencies...
2018/11/26 22:36:35 Output from dependency scanning: Error: unexpected EOF
Error: failed to run step ID: build: failed to scan dependencies: exit status 1
```

Extension version: 0.4.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (1.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

### PR DESCRIPTION
**Pull request by rosanch**
Tested error #650 with dockerfile from the user's repo.
Issue #635 fixed. The error is now handled properly.

### CODE REVIEW

File: commands/utils/quick-pick-azure.ts [hunk 1]
```diff
@@ -149,7 +149,9 @@ export async function confirmUserIntent(yesOrNoPrompt: string): Promise<boolean>
     let answer = await ext.ui.showInputBox(opt);
     answer = answer.toLowerCase();
     if (answer === 'yes') {
-        return answer === 'yes';
+        return true;
+    } else if (!cancelWhenNo && answer === 'no') {
+        return false;
```
Comment (StephenWeatherford) [inline commands/utils/quick-pick-azure.ts]: So what if they enter "true" or something?  Right now, the code would throw UserCancelled regardless of cancelWhenNo.

Suggest:

    } else if (!cancelWhenNo) {
  return false;
} else { 
        throw new UserCancelledError(); 
}

File: commands/utils/quick-pick-file.ts [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+import { DOCKERFILE_GLOB_PATTERN, YAML_GLOB_PATTERN } from '../../dockerExtension';
+import { ext } from '../../extensionVariables';
+
+export interface Item extends vscode.QuickPickItem {
+    relativeFilePath: string;
+    relativeFolderPath: string;
+}
+
+async function getFileUris(folder: vscode.WorkspaceFolder, globPattern: string): Promise<vscode.Uri[]> {
+    return await vscode.workspace.findFiles(new vscode.RelativePattern(folder, globPattern), undefined, 1000, undefined);
```
Comment (StephenWeatherford) [inline commands/utils/quick-pick-file.ts]: Use constant for 1000

File: commands/utils/quick-pick-azure.ts (hunk 1 above)
Comment (StephenWeatherford) [reply commands/utils/quick-pick-azure.ts]: The callers both look like this:
>     const should = await confirmUserIntent(`Are you sure?`);
>     if (should) {
>          … do some stuff
>     }

If user:
  types "yes" - does the work
  presses ESC - telemetry says it was cancelled
  types "no" - doesn't do the work, but telemetry says it did and that it succeeded

Seems to me the last two cases should be the same (in which case there's no need to return a Boolean. Otherwise, not sure what you would want to do differently.

Comment (rosanch) [reply commands/utils/quick-pick-azure.ts]: But then how you would recommend handling the options for a "pull from Azure". Right now handle a repo or an image. Both are the same command. 
Should I split the command into 2 instead?

Comment (StephenWeatherford) [reply commands/utils/quick-pick-azure.ts]: I don't understand the scenario.  Why do you want different behavior for ESC versus typing in No?

Comment (StephenWeatherford) [reply commands/utils/quick-pick-azure.ts]: Typing in Yes should only be for confirming a major operation such as a delete.  Simple yes/no should be yes/no buttons.

Comment (rosanch) [reply commands/utils/quick-pick-azure.ts]: I changed it, I agree with you. It is better to use this for  major operations

**Comment by rosanch** [comment]
Fixes #679
