### PR TITLE
Handle errors in getchildren

### LINKED ISSUE #818: Correctly parse errors
Example:

1) Try logging in to Docker Hub, but give an incorrect password
!)Error Message that doesn't go through our shared handler: {"password":["Ensure this value has at least 5 characters (it has 3)."]}

### PR DESCRIPTION
**Pull request by StephenWeatherford**
For next release...

Fixes #818

### CODE REVIEW

File: explorer/models/taskNode.ts [hunk 1]
```diff
@@ -43,26 +44,33 @@ export class TaskRootNode extends NodeBase {
...
-            const learnHow: vscode.MessageItem = { title: "Learn How to Create Build Tasks" };
-            vscode.window.showInformationMessage(`You do not have any Tasks in the registry '${element.registry.name}'.`, learnHow).then(val => {
-                if (val === learnHow) {
-                    // tslint:disable-next-line:no-unsafe-any
-                    opn('https://aka.ms/acr/task');
-                }
-            })
-        }
+        // tslint:disable-next-line:no-this-assignment
+        let me = this;
```
Comment (nturinski) [inline explorer/models/taskNode.ts]: Looks like this assignment here isn't used.
