### PR TITLE
Clearer error message for duplicate registry

### LINKED ISSUE #1310: Cannot connect to Azure container registry from Docker extension
I have the lastest Docker 0.8.1 and several Azure extensions: Azure App Insights, Azure CLI Tools, and Azure Dev Spaces as of 9/26/2019.  There seems to be an error or conflict connecting to Azure with the Docker extension.  

Repro steps:

1. Docker Registries: Connect Registry.. from command pallette
2. Choose Azure

Action: vscode-docker.registries.connectRegistry
Error type: Error
Error Message: Only one provider with id "azure" is allowed at a time.

Version: 0.8.1
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
RegistriesTreeItem.connectRegistry extension.bundle.js:332:362455
```

</details>

### PR DESCRIPTION
**Pull request by bwateratmsft**
Resolves #1310

The user will see a clear warning message instead:
image

### CODE REVIEW

**Comment by bwateratmsft** [comment]
> Lets Prove it

*sigh*
Begone, bot.

File: src/tree/registries/RegistriesTreeItem.ts [hunk 1]
```diff
@@ -98,7 +98,9 @@ export class RegistriesTreeItem extends AzExtParentTreeItem {
             context.telemetry.properties.cancelStep = 'learnHowToContribute';
             throw new UserCancelledError();
         } else if (provider.onlyOneAllowed && this._cachedProviders.find(c => c.id === provider.id)) {
-            throw new Error(`Only one provider with id "${provider.id}" is allowed at a time.`);
+            await ext.ui.showWarningMessage(`The "${provider.id}" registry provider is already connected.`);
```
Comment (philliphoff) [inline src/tree/registries/RegistriesTreeItem.ts]: Can we use the `label` rather than the `id` as the latter is not necessarily intended for human consumption and therefore might be confusing?

Comment (bwateratmsft) [reply src/tree/registries/RegistriesTreeItem.ts]: Yes, that's a better idea than what I had.

image
