### PR TITLE
Change context type determination

### LINKED ISSUE #2452: Extension fails to load with latest Docker edge
Repro steps:

1. Install latest Docker Edge candidate:  
      https://desktop-stage.docker.com/win/edge/49266/Docker%20Desktop%20Installer.exe
      https://desktop-stage.docker.com/mac/edge/49266/Docker.dmg
2. Overwrite Docker executable with the one from https://github.com/docker/compose-cli/releases/tag/v1.0.0
   On Mac you might need to do `sudo xattr -rc /Applications/Docker.app` to disable signature checking and the "application is damaged" error.
3. Open Docker extension

Expected: extension works

Actual: extension does not load with `Cannot read property 'Name' of undefined` error

The issue is in ContextManager.ts line 222: the output of `context ls --format "{{json .}}"` is now a single line of JSON, not one line per context, for example:

```shell
[{"Current":false,"Description":"rg-aci-play@westus2","DockerEndpoint":"","KubernetesEndpoint":"","Type":"aci","Name":"acictx","StackOrchestrator":""},{"Current":true,"Description":"Current DOCKER_HOST based configuration","DockerEndpoint":"unix:///var/run/docker.sock","KubernetesEndpoint":"","Type":"moby","Name":"default","StackOrchestrator":"swarm"},{"Current":false,"Description":"rg-guestbookexpress@westus2","DockerEndpoint":"","KubernetesEndpoint":"","Type":"aci","Name":"gbexpress","StackOrchestrator":""}]
```

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2452

### CODE REVIEW

File: src/docker/ContextManager.ts [hunk 1]
```diff
@@ -218,21 +220,37 @@ export class DockerContextManager implements ContextManager, Disposable {
...
-            for (const line of lines) {
-                // Blank lines should be skipped
-                if (!line) {
-                    continue;
+            try {
+                // Try parsing as-is; newer CLIs output a JSON object array
+                const contexts = JSON.parse(stdout) as DockerContext[];
+
+                result.push(...contexts.map(context => {
+                    return {
```
Comment (philliphoff) [inline src/docker/ContextManager.ts:231]: Perhaps consolidate conversion of `DockerContext` objects to avoid duplication (such as the logic for setting `ContextType`)?

**Review by philliphoff — APPROVED** [review]
