### PR TITLE
Filter issues

### LINKED ISSUE #739: Error show logs if there are no running containers
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: vscode-docker.container.show-logs
Error type: Error
Error Message: There are no Docker containers that apply to this command.

Version: 0.5.1
OS: win32

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #739 by removing "running" filter for show logs.

Also improves code quality.

### CODE REVIEW

File: commands/remove-container.ts [hunk 1]
```diff
@@ -8,8 +8,8 @@ import { IActionContext } from 'vscode-azureextensionui';
 import { dockerExplorerProvider } from '../dockerExtension';
 import { ContainerNode } from '../explorer/models/containerNode';
 import { RootNode } from '../explorer/models/rootNode';
-import { docker } from './utils/docker-endpoint';
-import { ContainerItem, quickPickContainer } from './utils/quick-pick-container';
+import { AllStatusFilter, docker, ListContainerDescOptions } from './utils/docker-endpoint';
+import { ContainerItem, quickPickContainer, quickPickContainerOrAll as quickPickContainerOrAll } from './utils/quick-pick-container';
```
Comment (EricJizbaMSFT) [inline commands/remove-container.ts]: What's with `quickPickContainerOrAll as quickPickContainerOrAll`

Comment (StephenWeatherford) [reply commands/remove-container.ts]: Huh.  Must've been auto-magicked, will remove.
