### PR TITLE
Slightly improve terminal output

### LINKED ISSUE #3691: The logs are messy in Terminal window when debugging a .NET project
**OS:** Win 10
**Build Version:** 20221108.4

**Repro Steps:**
1. Open a .NET MVC project and add docker files to it in VS Code.
2. Debug this project with configuration "Docker .NET Core Launch".
3. Check the logs in Terminal window.

**Expect:**
The logs are clear and easy to see.

**Actual:**
The logs are messy in Terminal window.
image

**More Info:**
This issue can be easily reproduced when debugging the project at the first time.

### PR DESCRIPTION
**Pull request by bwateratmsft**
This fixes #3691 as far as we can reasonably go without dumping `Pseudoterminal` / `CustomExecution`.

### CODE REVIEW

File: src/tasks/DockerPseudoterminal.ts [hunk 1]
```diff
@@ -3,15 +3,15 @@
  *  Licensed under the MIT License. See LICENSE.md in the project root for license information.
  *--------------------------------------------------------------------------------------------*/
 
+import { CancellationToken, CancellationTokenSource, Event, EventEmitter, Pseudoterminal, TaskScope, TerminalDimensions, workspace, WorkspaceFolder } from 'vscode';
```
Comment (bwateratmsft) [inline src/tasks/DockerPseudoterminal.ts:6]: The recently-enabled import sorting in action

Comment (karolz-ms) [reply src/tasks/DockerPseudoterminal.ts:6]: 😒

**Review by karolz-ms — APPROVED** [review]
