### PR TITLE
Scaffold with configureSsl false when it's clear

### LINKED ISSUE #2076: [Suggestion] Add a warning message to remind to use the port 443 if use the https certificate
**OS:** Mac
**Build version:** 1.3.1-alpha
**.NET Core SDK:** 2.1

**Repro Steps:**

1. Create a .NET Core MVC project by "dotnet new mvc".
2. Open the project in VS Code --> Prompt to add the required asserts --> Yes.
3. F1 --> Type and select "Docker: Add Docker Files to Workspace" --> ASP.NET Core --> Linux --> Include optional Docker Compose files --> Port: 80.
4. Go to the Debug tab in VSCode, select the "Docker .NET Core Launch"-->F5

**Actual:**
It doesn't launch the browser and open the web page without any warning.

**Suggestion:**
Add a warning message to remind to use the port 443 if use the https certificate.

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2076

### CODE REVIEW

File: src/tasks/netcore/NetCoreTaskHelper.ts [hunk 1]
```diff
@@ -99,6 +99,9 @@ export class NetCoreTaskHelper implements TaskHelper {
         options.appProject = options.appProject || await NetCoreTaskHelper.inferAppProject(context.folder); // This method internally checks the user-defined input first
         options.platformOS = options.platformOS || 'Linux';
 
+        // If there's exactly one port and it's 80, then set configureSsl to false, otherwise leave it undefined
```
Comment (karolz-ms) [inline src/tasks/netcore/NetCoreTaskHelper.ts:102]: Will the `configureSsl: undefined` show up in tasks.json after this change? If yes, can we avoid that? In general it is preferable to avoid explicit configuration if defaults are used.

Comment (bwateratmsft) [reply src/tasks/netcore/NetCoreTaskHelper.ts:102]: No, fortunately! It does exactly what we want:

When you pass in `configureSsl: undefined`:
```json
"netCore": {
    "appProject": "${workspaceFolder}/MVC3.csproj",
    "enableDebugging": true
}
```

And `false`:
```json
"netCore": {
    "appProject": "${workspaceFolder}/MVC3.csproj",
    "enableDebugging": true,
    "configureSsl": false
}
```
