### PR TITLE
Change to removing images by name

### LINKED ISSUE #1529: Feature to find dependent child images
While I understand the error, it'd be great if there was a feature that helped me determine what child images were causing this error:

image

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #1529, #333 (both indirectly).

If we remove by name instead of by ID, then the 409 conflict error won't happen anymore. If there are child images, then this will simply remove the tag of the parent image; later on if the child is removed it will also remove this parent image (assuming there aren't any other tags).

### CODE REVIEW

File: src/commands/images/removeImage.ts [hunk 1]
```diff
@@ -21,9 +21,9 @@ export async function removeImage(context: IActionContext, node?: ImageTreeItem,
 
     let confirmRemove: string;
     if (nodes.length === 1) {
-        confirmRemove = localize('vscode-docker.commands.images.remove.confirmSingle', 'Are you sure you want to remove image "{0}"? This will remove all matching and child images.', nodes[0].label);
+        confirmRemove = localize('vscode-docker.commands.images.remove.confirmSingle', 'Are you sure you want to remove image "{0}"? If there are other tags or child images, only the tag will be removed.', nodes[0].fullTag);
     } else {
-        confirmRemove = localize('vscode-docker.commands.images.remove.confirmMulti', 'Are you sure you want to remove selected images? This will remove all matching and child images.');
+        confirmRemove = localize('vscode-docker.commands.images.remove.confirmMulti', 'Are you sure you want to remove the selected images? If there are other tags or child images, only the tag will be removed.');
```
Comment (karolz-ms) [inline src/commands/images/removeImage.ts]:
```suggestion
        confirmRemove = localize('vscode-docker.commands.images.remove.confirmMulti', 'Are you sure you want to remove the selected images? If there are other tags or child images for this image, only the tag will be removed.');
```

Comment (karolz-ms) [reply src/commands/images/removeImage.ts]: (plus similar change for the confirmation message above)

File: src/commands/images/removeImage.ts [hunk 2]
```diff
@@ -21,9 +21,9 @@ export async function removeImage(context: IActionContext, node?: ImageTreeItem,
 
     let confirmRemove: string;
     if (nodes.length === 1) {
-        confirmRemove = localize('vscode-docker.commands.images.remove.confirmSingle', 'Are you sure you want to remove image "{0}"? This will remove all matching and child images.', nodes[0].label);
+        confirmRemove = localize('vscode-docker.commands.images.remove.confirmSingle', 'Are you sure you want to remove image "{0}"? If there are other tags or child images for this image, only the tag will be removed.', nodes[0].fullTag);
     } else {
-        confirmRemove = localize('vscode-docker.commands.images.remove.confirmMulti', 'Are you sure you want to remove selected images? This will remove all matching and child images.');
+        confirmRemove = localize('vscode-docker.commands.images.remove.confirmMulti', 'Are you sure you want to remove the selected images? If there are other tags or child images for this image, only the tag will be removed.');
```
Comment (karolz-ms) [inline src/commands/images/removeImage.ts]:
```suggestion
        confirmRemove = localize('vscode-docker.commands.images.remove.confirmMulti', 'Are you sure you want to remove the selected images? If there are other tags or child images for these images, only the selected tags will be removed.');
```
Sorry, should have suggested this first time :-*)

Comment (bwateratmsft) [reply src/commands/images/removeImage.ts]: English is imprecise...it's on a per-image basis; i.e. if only one of the images has children, we'll still be removing the others (just not this one). Hard to convey that....

Comment (karolz-ms) [reply src/commands/images/removeImage.ts]: OK, then never mind, no biggie

Comment (bwateratmsft) [reply src/commands/images/removeImage.ts]: In any case I changed `this image` -> `these images`.

File: src/tree/images/ImageTreeItem.ts [hunk 3]
```diff
@@ -59,25 +57,11 @@ export class ImageTreeItem extends AzExtTreeItem {
     }
 
     public async getImage(): Promise<Image> {
-        return callDockerode(() => ext.dockerode.getImage(this.imageId));
+        return callDockerode(() => ext.dockerode.getImage(this.fullTag));
```
Comment (bwateratmsft) [inline src/tree/images/ImageTreeItem.ts]: Removal fails here for images that are tagged `<none>`, i.e. those where a newer version of the same image has been downloaded.

File: src/commands/images/runImage.ts [hunk 4]
```diff
@@ -26,7 +27,7 @@ async function runImageCore(context: IActionContext, node: ImageTreeItem | undef
     }
 
     const image = await node.getImage();
-    const inspectInfo = await image.inspect();
+    const inspectInfo = await callDockerode(async () => image.inspect());
```
Comment (ravipal) [inline src/commands/images/runImage.ts]: Why do we need callDockerrode now?

Comment (bwateratmsft) [reply src/commands/images/runImage.ts:30]: This spot should've had it prior to now. Karol's context changes make flowing through `callDockerode` preferable, because it handles checking for context switches.
