### PR TITLE
Miscellaneous fixes

### LINKED ISSUE #1419: F5 without any .vscode folder has bad behavior
1. Create a .NET Core project with `dotnet new`
1. Open the folder in VSCode
1. When the prompt about required assets comes up, click "not now"
1. Hit F5
1. VSCode prompts on environment, showing .NET Core and the new and old Docker .NET Core debugging. Pick a .NET Core choice.

Both Docker options result in bad behavior. Instead we should throw an error saying to add it with "Add Docker Files..."

I think it calls provideInitialDebugConfigurations, which comes back with nothing in our extension.

### LINKED ISSUE #1421: Validate that spaces don't mess up .NET Core targets magic
For .NET Core projects we use a special project file to determine the output binary path, and a special targets file to determine the Blazor manifest input/output location.

Need to verify that spaces somewhere in those paths do not break the logic, since user directories may contain spaces.

### PR DESCRIPTION
**Pull request by bwateratmsft**
Resolves #1419
Resolves #1421

Also resolves the path issue @haniamr ran into.

### CODE REVIEW

File: src/debugging/DockerDebugConfigurationProvider.ts [hunk 1]
```diff
@@ -24,7 +24,8 @@ export class DockerDebugConfigurationProvider implements DebugConfigurationProvi
     ) { }
 
     public provideDebugConfigurations(folder: WorkspaceFolder | undefined, token?: CancellationToken): ProviderResult<DebugConfiguration[]> {
-        return undefined;
+        window.showErrorMessage("To debug in a Docker container on supported platforms, use the command \"Docker: Add Docker Files to Workspace\".");
```
Comment (philliphoff) [inline src/debugging/DockerDebugConfigurationProvider.ts]: Nit: use single quotes for strings.

Comment (philliphoff) [inline src/debugging/DockerDebugConfigurationProvider.ts]: Couldn't they also use the "initialize for debugging" command, too?

Comment (philliphoff) [reply src/debugging/DockerDebugConfigurationProvider.ts]: Should we show an error message with button(s) to immediately run either of those commands?

Comment (bwateratmsft) [reply src/debugging/DockerDebugConfigurationProvider.ts]: They could do both, but I'm guessing that most people running into this situation have not added Docker support in the first place. For future projects, if they had, it would already have the debug configuration and they wouldn't hit this.

The Add workflow does ask before overwriting, so IMO it's safe.

We can add a button, shouldn't be difficult.

File: src/debugging/DockerDebugConfigurationProvider.ts [hunk 2]
```diff
@@ -24,7 +24,18 @@ export class DockerDebugConfigurationProvider implements DebugConfigurationProvi
     ) { }
 
     public provideDebugConfigurations(folder: WorkspaceFolder | undefined, token?: CancellationToken): ProviderResult<DebugConfiguration[]> {
-        return undefined;
+        const add: MessageItem = { title: 'Add Docker Files' };
+
+        // Prompt them to add Docker files since they probably haven't
+        window.showErrorMessage(
+            'To debug in a Docker container on supported platforms, use the command \"Docker: Add Docker Files to Workspace\", or click the button below.',
```
Comment (philliphoff) [inline src/debugging/DockerDebugConfigurationProvider.ts]: Nit: if I recall, it's preferable not to refer to the relative positions of things in the UX, as it's not always obvious what that means when using assistive technologies (e.g. screen readers).  It may be better to refer to the button by its name.
