### PR TITLE
Fix tests silently failing

### LINKED ISSUE #2302: Tests are failing silently
Tests have been failing but are doing so silently. e.g. https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=25608

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #2302. Also unrelatedly, slightly improves the fix for #2313.

### CODE REVIEW

File: src/debugging/python/PythonDebugHelper.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class PythonDebugHelper implements DebugHelper {
                 removeContainerAfterDebug: debugConfiguration.removeContainerAfterDebug
             },
             debugLauncherPath: debugConfiguration.debugLauncherPath || launcherPath,
-            debugAdapterHost: debugConfiguration.debugAdapterHost || await this.getDebugAdapterHost(context),
+            debugAdapterHost: debugConfiguration.debugAdapterHost || await this.getDebugAdapterHost(context) || '172.17.0.1',
```
Comment (karolz-ms) [inline src/debugging/python/PythonDebugHelper.ts:97]: What is this IP address, why is this one a good default?

Comment (bwateratmsft) [reply src/debugging/python/PythonDebugHelper.ts:97]: This is the IP address that represents the host within the container, on the `bridge` network. So far this is the only one I've ever seen--same address on my Windows desktop, Macbook, Linux VM, and multiple customers' Linux machines as well.

Their [docs](https://docs.docker.com/network/network-tutorial-standalone/) explicitly mention that address as well (for `bridge`), but it may be more as an example than a prescriptive statement.

Comment (karolz-ms) [reply src/debugging/python/PythonDebugHelper.ts:97]: Roger. Internet poking suggests 172.17.0.0/16 is the default bridge network address space. I would just put a comment on that in the code then

**Review by karolz-ms — APPROVED** [review]
